server:
  port: '8084'
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/swag
    username : root
    password : 123456789
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

