server:
  port: '8083'
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/boot
    username : root
    password : 123456789
    driverClassName : com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto : none

